"""11a-ii: add scope_id to schema_snapshots and entity_definitions

Revision ID: 6431387ee0ff
Revises: dced02af0d0f
Create Date: 2026-04-20 10:58:39.618167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6431387ee0ff'
down_revision: Union[str, Sequence[str], None] = 'dced02af0d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_definitions', sa.Column('scope_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_entity_definitions_scope_id'), 'entity_definitions', ['scope_id'], unique=False)
    op.create_foreign_key(None, 'entity_definitions', 'scopes', ['scope_id'], ['id'], ondelete='RESTRICT')
    op.add_column('schema_snapshots', sa.Column('scope_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_schema_snapshots_scope_id'), 'schema_snapshots', ['scope_id'], unique=False)
    op.create_foreign_key(None, 'schema_snapshots', 'scopes', ['scope_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schema_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_schema_snapshots_scope_id'), table_name='schema_snapshots')
    op.drop_column('schema_snapshots', 'scope_id')
    op.drop_constraint(None, 'entity_definitions', type_='foreignkey')
    op.drop_index(op.f('ix_entity_definitions_scope_id'), table_name='entity_definitions')
    op.drop_column('entity_definitions', 'scope_id')
    # ### end Alembic commands ###
