"""Add reopened_at to entity_definitions

Revision ID: b751f9802867
Revises: fbef26df9e06
Create Date: 2026-04-19 14:41:00.313949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b751f9802867'
down_revision: Union[str, Sequence[str], None] = 'fbef26df9e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_definitions', sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_definitions', 'reopened_at')
    # ### end Alembic commands ###
