"""Initial schema: snapshots and entity definitions

Revision ID: fbef26df9e06
Revises: 
Create Date: 2026-04-19 12:37:12.306475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbef26df9e06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_database', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('proposed_by', sa.String(length=64), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.String(length=64), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('source_snapshot_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['entity_definitions.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['schema_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['entity_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_definitions_source_snapshot_id'), 'entity_definitions', ['source_snapshot_id'], unique=False)
    op.create_index(op.f('ix_entity_definitions_status'), 'entity_definitions', ['status'], unique=False)
    op.create_table('snapshot_tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('database_name', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('primary_key_columns', sa.Text(), nullable=True),
    sa.Column('row_count_estimate', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['schema_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'schema_name', 'table_name', name='uq_snapshot_table')
    )
    op.create_index(op.f('ix_snapshot_tables_snapshot_id'), 'snapshot_tables', ['snapshot_id'], unique=False)
    op.create_table('snapshot_columns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('datum_type', sa.String(length=32), nullable=False),
    sa.Column('native_type', sa.String(length=255), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('sample_values_json', sa.Text(), nullable=True),
    sa.Column('distinct_sample_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['snapshot_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'column_name', name='uq_snapshot_column')
    )
    op.create_index(op.f('ix_snapshot_columns_table_id'), 'snapshot_columns', ['table_id'], unique=False)
    op.create_table('entity_source_columns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_column_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_column_id'], ['snapshot_columns.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_source_columns_entity_id'), 'entity_source_columns', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_source_columns_snapshot_column_id'), 'entity_source_columns', ['snapshot_column_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_source_columns_snapshot_column_id'), table_name='entity_source_columns')
    op.drop_index(op.f('ix_entity_source_columns_entity_id'), table_name='entity_source_columns')
    op.drop_table('entity_source_columns')
    op.drop_index(op.f('ix_snapshot_columns_table_id'), table_name='snapshot_columns')
    op.drop_table('snapshot_columns')
    op.drop_index(op.f('ix_snapshot_tables_snapshot_id'), table_name='snapshot_tables')
    op.drop_table('snapshot_tables')
    op.drop_index(op.f('ix_entity_definitions_status'), table_name='entity_definitions')
    op.drop_index(op.f('ix_entity_definitions_source_snapshot_id'), table_name='entity_definitions')
    op.drop_table('entity_definitions')
    op.drop_table('schema_snapshots')
    # ### end Alembic commands ###
